### ISSUE TITLE
Hello World in Racket

### ISSUE THREAD

**Issue by Padmaksh-Mishra** [GDSC-SGGSCC/Hacktoberfest-22#137]
A simple hello world in racket

**Comment by Padmaksh-Mishra** [comment]
please assign me this

**Comment by Padmaksh-Mishra** [comment]
This is my solution 
https://github.com/GDSC-SGGSCC/Hacktoberfest-22/pull/138#issue-1403326144

**Comment by reveurguy** [comment]
i will check the pr
